[package]
name = "charsiug2p-g2p-tokenizer"
version = "0.1.0"
edition = "2021"

[lib]
name = "charsiug2p_g2p_tokenizer"
crate-type = ["lib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokenizers = "0.15"
